# Generated by Django 5.2.5 on 2025-08-20 03:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên danh mục sản phẩm', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về danh mục', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động của danh mục')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo danh mục')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối cùng')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'demo_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='demo_catego_name_89b35c_idx'), models.Index(fields=['is_active', 'created_at'], name='demo_catego_is_acti_d33ac9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Mã đơn hàng', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('shipped', 'Đã gửi hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Tổng tiền đơn hàng', max_digits=10)),
                ('shipping_address', models.TextField(help_text='Địa chỉ giao hàng')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú đơn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'demo_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên sản phẩm', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version của tên sản phẩm', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Mô tả chi tiết sản phẩm')),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá sản phẩm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá khuyến mãi (nếu có)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Số lượng tồn kho')),
                ('rating', models.FloatField(default=0.0, help_text='Đánh giá trung bình (0-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ')], default='draft', help_text='Trạng thái sản phẩm', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Sản phẩm nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Danh mục sản phẩm', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='models_demo.category')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'demo_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Số lượng sản phẩm')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Đơn giá tại thời điểm đặt hàng', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Tổng tiền cho sản phẩm này', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='models_demo.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='models_demo.product')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'demo_order_items',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hình ảnh sản phẩm', upload_to='products/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, help_text='Mô tả hình ảnh cho SEO', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Hình ảnh chính của sản phẩm')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Thứ tự hiển thị hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='models_demo.product')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
                'db_table': 'demo_product_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Đánh giá từ 1-5 sao', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Tiêu đề đánh giá', max_length=200)),
                ('comment', models.TextField(help_text='Nội dung đánh giá chi tiết')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Xác nhận mua hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='models_demo.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
                'db_table': 'demo_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên tag', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version của tag', unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Màu sắc của tag (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='models_demo.product')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'demo_tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='demo_orders_user_id_964f23_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='demo_orders_status_0ddad6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='demo_orders_order_n_33ec25_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='demo_produc_categor_db4029_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='demo_produc_price_399a57_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='demo_produc_rating_fc3869_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='demo_produc_is_feat_5cf023_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='rating_range'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='demo_order__order_i_6ff14c_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='demo_produc_product_04b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['order'], name='demo_produc_order_0bb284_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'is_primary'), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='demo_review_product_e426e0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created_at'], name='demo_review_user_id_b9838c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase', 'rating'], name='demo_review_is_veri_067e03_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_review_per_user_per_product'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='demo_tags_name_ea169b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='demo_tags_slug_a7d8e4_idx'),
        ),
    ]
